### ISSUE TITLE
The library is compiled without QT support in function displayOverlay

### ISSUE THREAD

**Issue by ryukinix** [Cartucho/yolo-boundingbox-labeler-GUI#2]
```
~/Desktop/yolo-boundingbox-labeler-GUI master
❯ python run.py
OpenCV Error: The function/feature is not implemented (The library is compiled without QT support) in displayOverlay, file /build/opencv/src/opencv-3.4.0/modules/highgui/src/window.cpp, line 528
Traceback (most recent call last):
  File "run.py", line 203, in <module>
    change_img_index(0)
  File "run.py", line 25, in change_img_index
    "" + str(last_img_index), 1000)
cv2.error: /build/opencv/src/opencv-3.4.0/modules/highgui/src/window.cpp:528: error: (-213) The library is compiled without QT support in function displayOverlay
```

**Comment by Cartucho** [comment]
Could you recompile OpenCV using WITH_QT=ON ?

**Comment by Cartucho** [comment]
@ryukinix Did it work?

**Comment by INNFINITEMINDS** [comment]
sir!!!
i also getting same erroro please help !!!!
also tell me hoe to solve ethis error ? 
also how can we recompile OpenCV using WITH_QT=ON ?


please help !!!!!!!
###############################################
i m using python  3.6.3 version
error !!!!!!!!!!!!!!!!!!!!!!!
OpenCV Error: The function/feature is not implemented (The library is compiled without QT support) in cv::displayOverlay, file D:\Build\OpenCV\opencv-3.4.0\modules\highgui\src\window.cpp, line 528
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\yolo-boundingbox-labeler-GUI\try.py", line 221, in <module>
    change_img_index(0)
  File "C:\Users\admin\Desktop\yolo-boundingbox-labeler-GUI\try.py", line 22, in change_img_index
    "" + str(last_img_index), 1000)
cv2.error: D:\Build\OpenCV\opencv-3.4.0\modules\highgui\src\window.cpp:528: error: (-213) The library is compiled without QT support in function cv::displayOverlay

[Finished in 0.357s]


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Cartucho** [comment]
@INNFINITEMINDS 
How did you install OpenCV? Which method?

I uploaded the [question on StackOverflow](https://stackoverflow.com/questions/48808179/opencv-windows-the-library-is-compiled-without-qt-support-in-function-displayo)

**Comment by Cartucho** [comment]
@INNFINITEMINDS 
Qt has this tutorial on [how to set Qt and OpenCV on Windows](https://wiki.qt.io/How_to_setup_Qt_and_openCV_on_Windows).

**Comment by MattKleinsmith** [comment]
I installed opencv with pip and things are working for me:

`pip install opencv-python`

My environment:

Ubuntu 16.04, Python 3.6.3, Anaconda 5.0.1

**Comment by INNFINITEMINDS** [comment]
hello!!
i have installed opencv by downloading windows binary and then i use commAND PROPMT TO INSTALL THEM!!


HOW TO SOLVE THIS ERROR??

**Comment by PTS93** [comment]
Using pip install opencv-python on Windows 10 seems to install a version that also doesn't have QT support compiled into it.

**Comment by Cartucho** [comment]
@PTS93 this weekend I will make a video on: "How to Install OpenCV3.4 on Windows with Qt";
I will share it here as soon as I have it.

**Comment by Cartucho** [comment]
So I managed to install it but it took 4 hours...   
Turns OpenCV did not make things easy for Windows users ... :-1:

I decided that I will implement the functions using QT by myself (Zoom in and Zoom out).

It turns out that [OpenCV wants to drop QT](https://github.com/opencv/opencv/wiki/GSoC_2018#8-highgui) anyway.

**Comment by INNFINITEMINDS** [comment]
ARE U GOING TO MAKE A VIDEO ON IT ?

**Comment by Cartucho** [comment]
@INNFINITEMINDS  could you please download the latest release and run that code?

This error shouldn't be occurring anymore. Without QT Zoom doesn't work but the rest works fine.

**Comment by INNFINITEMINDS** [comment]
again i have tried and i m geting same error!!
error as follows >:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::




OpenCV Error: The function/feature is not implemented (The library is compiled without QT support) in cv::displayOverlay, file D:\Build\OpenCV\opencv-3.3.1\modules\highgui\src\window.cpp, line 528
Traceback (most recent call last):
  File "C:\Users\INFINITY\Desktop\yolo-boundingbox-labeler-GUI-master\run.py", line 327, in <module>
    change_img_index(0)
  File "C:\Users\INFINITY\Desktop\yolo-boundingbox-labeler-GUI-master\run.py", line 37, in change_img_index
    "" + str(last_img_index), 1000)
cv2.error: D:\Build\OpenCV\opencv-3.3.1\modules\highgui\src\window.cpp:528: error: (-213) The library is compiled without QT support in function cv::displayOverlay

[Finished in 8.026s]
Linter
Severity 	Provider 	Description	Line 
run.py000419:1
LF1 deprecationUTF-8Python0 files9:22

**Comment by Cartucho** [comment]
@INNFINITEMINDS  are you sure you are using the latest release code? Your error message shows otherwise. E.g:  "" + str(last_img_index), 1000) is not in line 37 .

**Comment by INNFINITEMINDS** [comment]
can u please  make a video on it i m unabel to start this:..i m getting same error

**Comment by INNFINITEMINDS** [comment]
i have insatalled python 3 on windows with the help of anaconda
now what should i have to do to run your script ?
help required

**Comment by arvind-cp** [comment]
I was getting this error with png images but works fine with jpg.

**Comment by arvind-cp** [comment]
Right. Thx.

**Comment by aishkul1012** [comment]
> sir!!!
> i also getting same erroro please help !!!!
> also tell me hoe to solve ethis error ?
> also how can we recompile OpenCV using WITH_QT=ON ?
> 
> please help !!!!!!!
> ###############################################
> i m using python 3.6.3 version
> error !!!!!!!!!!!!!!!!!!!!!!!
> OpenCV Error: The function/feature is not implemented (The library is compiled without QT support) in cv::displayOverlay, file D:\Build\OpenCV\opencv-3.4.0\modules\highgui\src\window.cpp, line 528
> Traceback (most recent call last):
> File "C:\Users\admin\Desktop\yolo-boundingbox-labeler-GUI\try.py", line 221, in
> change_img_index(0)
> File "C:\Users\admin\Desktop\yolo-boundingbox-labeler-GUI\try.py", line 22, in change_img_index
> "" + str(last_img_index), 1000)
> cv2.error: D:\Build\OpenCV\opencv-3.4.0\modules\highgui\src\window.cpp:528: error: (-213) The library is compiled without QT support in function cv::displayOverlay
> 
> [Finished in 0.357s]
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Hey Could you tell me how you solved this problem?
Facing the same error right now!

**Comment by DragonDoctor2033** [comment]
Same for me. Still get the same error. Install OpenCV from pyCharm terminal pip install. Any solutions?

**Comment by reemastha706** [comment]
I know the post is quite old. But I am running into the same problem. Anyone who got it solved? Based on another post on how to use qt with opencv, i downgraded the opencv version, but it's not working.

**Comment by Xaego** [comment]
https://wiki.qt.io/How_to_setup_Qt_and_openCV_on_Windows
